<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
           "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<title>Coverage Report</title>
<link title="Style" type="text/css" rel="stylesheet" href="css/main.css"/>
<script type="text/javascript" src="js/popup.js"></script>
</head>
<body>
<h5>Coverage Report - com.t9.bussiness.dao.OrderManagementDaoImpl</h5>
<div class="separator">&nbsp;</div>
<table class="report">
<thead><tr>  <td class="heading">Classes in this File</td>  <td class="heading"><a class="dfn" href="help.html" onclick="popupwindow('help.html'); return false;">Line Coverage</a></td>  <td class="heading"><a class="dfn" href="help.html" onclick="popupwindow('help.html'); return false;">Branch Coverage</a></td>  <td class="heading"><a class="dfn" href="help.html" onclick="popupwindow('help.html'); return false;">Complexity</a></td></tr></thead>
  <tr><td><a href="com.t9.bussiness.dao.OrderManagementDaoImpl.html">OrderManagementDaoImpl</a></td><td><table cellpadding="0px" cellspacing="0px" class="percentgraph"><tr class="percentgraph"><td align="right" class="percentgraph" width="40">85%</td><td class="percentgraph"><div class="percentgraph"><div class="greenbar" style="width:85px"><span class="text">18/21</span></div></div></td></tr></table></td><td><table cellpadding="0px" cellspacing="0px" class="percentgraph"><tr class="percentgraph"><td align="right" class="percentgraph" width="40"><a class="dfn" href="help.html" onclick="popupwindow('help.html'); return false;">N/A</a></td><td class="percentgraph"><div class="percentgraph"><div class="na" style="width:100px"><span class="text"><a class="dfn" href="help.html" onclick="popupwindow('help.html'); return false;">N/A</a></span></div></div></td></tr></table></td><td class="value"><span class="hidden">1.0;</span>1</td></tr>

</table>
<div class="separator">&nbsp;</div>


<table cellspacing="0" cellpadding="0" class="src">
	<tr>  <td>
	
<table cellspacing="0" cellpadding="0" class="src">
 <#list dataList as dataCol>
  <tr>  
	<td class="numLine">&nbsp;${dataCol.leftLine}</td>
  	<td class="src"><pre class="src"><#if dataCol.srcUncovered??><span class="srcUncovered"></#if>&nbsp;${dataCol.leftCode}<#if dataCol.srcUncovered??></span></#if></pre></td>
	<td class="numLine">&nbsp;${dataCol.rightLine}</td>
  	<td class="src"><pre class="src"><#if dataCol.srcUncovered??><span class="srcUncovered"></#if>&nbsp;${dataCol.rightCode}<#if dataCol.srcUncovered??></span></#if></pre></td>
  </tr>
 </#list>
</table>

</td>  <td>

</td></tr>
</table>

<div class="footer">Report generated by <a href="http://cobertura.sourceforge.net/" target="_top">Cobertura</a> 1.9.4.1 on 14-3-20 下午10:45.</div>
</body>
</html>
