<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
           "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<title>Coverage Report</title>
<link title="Style" type="text/css" rel="stylesheet" href="css/main.css"/>
<link title="Style" type="text/css" rel="stylesheet" href="css/sortabletable.css"/>
<script type="text/javascript" src="js/popup.js"></script>
<script type="text/javascript" src="js/sortabletable.js"></script>
<script type="text/javascript" src="js/customsorttypes.js"></script>
</head>
<body>
<h5>File Report - add Files</h5>
<div class="separator">&nbsp;</div>
<table class="report" id="packageResults">
<thead><tr>  <td class="heading">修改文件列表()</td>  <td class="heading">lines</td>  <td class="heading">revers times</td><td class="heading">type</td> </tr></thead>
<tbody>
 <#list diffMap?keys as key>
  <tr><td><a href="${diffMap[key]}" onclick='location.href="${diffMap[key]}"'>${key}</a></td><td class="value">1</td><td class="value">1</td><td class="value">1</td></tr>
  </#list>
</tbody>
</table>
<table class="report" id="packageResults2">
<thead><tr>  <td class="heading">新增文件列表()</td>  <td class="heading">lines</td>  <td class="heading">revers times</td><td class="heading">type</td> </tr></thead>
<tbody>
 <#list noExistsMap?keys as key>
  <tr><td><a href="frame-summary-com.html" onclick='location.href="frame-sourcefiles-com.html"'>${key}</a></td><td class="value">${noExistsMap[key]}</td><td class="value">1</td><td class="value">1</td></tr>
  </#list>
</tbody>
</table>

<script type="text/javascript">
var packageTable = new SortableTable(document.getElementById("packageResults"),
    ["String", "Number", "Percentage", "Percentage", "FormattedNumber"]);
packageTable.sort(0);
</script>
<div class="footer">Report generated by <a href="http://cobertura.sourceforge.net/" target="_top">Cobertura</a> 1.9.4.1 on 14-3-20 下午10:45.</div>
</body>
</html>
